-- Seed Ghana SHS / TVET schools (655 unique names from SHSTVET_school_names.txt)
-- Source: data/shs-tvet-school-names.txt

INSERT INTO senior_high_schools (name, name_norm, school_type, region)
VALUES
  ('ABAKRAMPA SENIOR HIGH/TECH SCHOOL', 'abakrampa senior high/tech school', 'technical', NULL),
  ('ABEASEMAN COMM. DAY SENIOR HIGH SCHOOL', 'abeaseman comm day senior high school', 'shs', NULL),
  ('ABETIFI PRESBY SENIOR HIGH SCHOOL', 'abetifi presby senior high school', 'shs', NULL),
  ('ABOR SENIOR HIGH SCHOOL', 'abor senior high school', 'shs', NULL),
  ('ABRAFI SENIOR HIGH SCHOOL', 'abrafi senior high school', 'shs', NULL),
  ('ABUADI/TSREFE SENIOR HIGH SCHOOL', 'abuadi/tsrefe senior high school', 'shs', NULL),
  ('ABURAMAN SENIOR HIGH SCHOOL', 'aburaman senior high school', 'shs', NULL),
  ('ABURI GIRLS SENIOR HIGH SCHOOL', 'aburi girls senior high school', 'shs', NULL),
  ('ABUTIA SENIOR HIGH/TCHNICAL SCHOOL', 'abutia senior high/tchnical school', 'technical', NULL),
  ('ACCRA GIRLS SENIOR HIGH SCHOOL', 'accra girls senior high school', 'shs', NULL),
  ('ACCRA SENIOR HIGH SCHOOL', 'accra senior high school', 'shs', NULL),
  ('ACCRA WESLEY GIRLS SENIOR HIGH SCHOOL', 'accra wesley girls senior high school', 'shs', NULL),
  ('ACHERENSUA SENIOR HIGH SCHOOL', 'acherensua senior high school', 'shs', NULL),
  ('ACHIASE SENIOR HIGH SCHOOL', 'achiase senior high school', 'shs', NULL),
  ('ACHIMOTA SENIOR HIGH SCHOOL', 'achimota senior high school', 'shs', NULL),
  ('ACHINAKROM SENIOR HIGH SCHOOL', 'achinakrom senior high school', 'shs', NULL),
  ('ADA SENIOR HIGH SCHOOL', 'ada senior high school', 'shs', NULL),
  ('ADA SENIOR HIGH/TECH SCHOOL', 'ada senior high/tech school', 'technical', NULL),
  ('ADAKLU SENIOR HIGH SCHOOL', 'adaklu senior high school', 'shs', NULL),
  ('ADANKWAMAN SENIOR HIGH SCHOOL', 'adankwaman senior high school', 'shs', NULL),
  ('ADANWOMASE SENIOR HIGH SCHOOL', 'adanwomase senior high school', 'shs', NULL),
  ('ADEISO PRESBY SENIOR HIGH SCHOOL', 'adeiso presby senior high school', 'shs', NULL),
  ('ADIDOME SENIOR HIGH SCHOOL', 'adidome senior high school', 'shs', NULL),
  ('ADIEMBRA SENIOR HIGH SCHOOL', 'adiembra senior high school', 'shs', NULL),
  ('ADJEN KOTOKU SENIOR HIGH SCHOOL', 'adjen kotoku senior high school', 'shs', NULL),
  ('ADJENA SENIOR HIGH/TECH SCHOOL', 'adjena senior high/tech school', 'technical', NULL),
  ('ADJOAFUA COMM. SENIOR HIGH SCHOOL', 'adjoafua comm senior high school', 'shs', NULL),
  ('ADOBEWORA COMM. SENIOR HIGH SCHOOL', 'adobewora comm senior high school', 'shs', NULL),
  ('ADONTEN SENIOR HIGH SCHOOL', 'adonten senior high school', 'shs', NULL),
  ('ADU GYAMFI SENIOR HIGH SCHOOL', 'adu gyamfi senior high school', 'shs', NULL),
  ('ADUGYAMA COMM. SENIOR HIGH SCHOOL', 'adugyama comm senior high school', 'shs', NULL),
  ('ADUMAN SENIOR HIGH SCHOOL', 'aduman senior high school', 'shs', NULL),
  ('ADVENTIST GIRLS SENIOR HIGH SCHOOL, NTONSO', 'adventist girls senior high school, ntonso', 'shs', NULL),
  ('ADVENTIST SENIOR HIGH SCHOOL, KUMASI', 'adventist senior high school, kumasi', 'shs', NULL),
  ('AFADJATO SENIOR HIGH/TECH SCHOOL', 'afadjato senior high/tech school', 'technical', NULL),
  ('AFIFE SENIOR HIGH TECH SCHOOL', 'afife senior high tech school', 'technical', NULL),
  ('AFIGYAMAN SENIOR HIGH SCHOOL', 'afigyaman senior high school', 'shs', NULL),
  ('AFUA KOBI AMPEM GIRLS'' SENIOR HIGH SCHOOL', 'afua kobi ampem girls senior high school', 'shs', NULL),
  ('AGATE COMM. SENIOR HIGH SCHOOL', 'agate comm senior high school', 'shs', NULL),
  ('AGGREY MEM. A.M.E.ZION SENIOR HIGH SCHOOL', 'aggrey mem amezion senior high school', 'shs', NULL),
  ('AGONA FANKOBAA SENIOR HIGH SCHOOL', 'agona fankobaa senior high school', 'shs', NULL),
  ('AGONA NAMONWORA COMM.SENIOR HIGH SCHOOL', 'agona namonwora commsenior high school', 'shs', NULL),
  ('AGONA SENIOR HIGH/TECH SCHOOL', 'agona senior high/tech school', 'technical', NULL),
  ('AGOTIME SENIOR HIGH SCHOOL', 'agotime senior high school', 'shs', NULL),
  ('AGRIC NZEMA SENIOR HIGH SCHOOL, KUMASI', 'agric nzema senior high school, kumasi', 'shs', NULL),
  ('AHAFOMAN SENIOR HIGH/TECH SCHOOL', 'ahafoman senior high/tech school', 'technical', NULL),
  ('AHAMANSU ISLAMIC SENIOR HIGH SCHOOL', 'ahamansu islamic senior high school', 'shs', NULL),
  ('AHANTAMAN GIRLS'' SENIOR HIGH SCHOOL', 'ahantaman girls senior high school', 'shs', NULL),
  ('AKATSI SENIOR HIGH/TECH SCHOOL', 'akatsi senior high/tech school', 'technical', NULL),
  ('AKIM ASAFO SENIOR HIGH SCHOOL', 'akim asafo senior high school', 'shs', NULL),
  ('AKIM SWEDRU SENIOR HIGH SCHOOL', 'akim swedru senior high school', 'shs', NULL),
  ('AKOKOASO SENIOR HIGH/TECH SCHOOL', 'akokoaso senior high/tech school', 'technical', NULL),
  ('AKOME SENIOR HIGH/TECH SCHOOL', 'akome senior high/tech school', 'technical', NULL),
  ('AKONTOMBRA SENIOR HIGH SCHOOL', 'akontombra senior high school', 'shs', NULL),
  ('AKPAFU SENIOR HIGH/TECH SCHOOL', 'akpafu senior high/tech school', 'technical', NULL),
  ('AKRO SENIOR HIGH/TECH SCHOOL', 'akro senior high/tech school', 'technical', NULL),
  ('AKROFUOM SENIOR HIGH/TECH SCHOOL', 'akrofuom senior high/tech school', 'technical', NULL),
  ('AKROSO SENIOR HIGH/TECH SCHOOL', 'akroso senior high/tech school', 'technical', NULL),
  ('AKUMADAN SENIOR HIGH SCHOOL', 'akumadan senior high school', 'shs', NULL),
  ('AKUSE METHODIST SENIOR HIGH/TECH SCHOOL', 'akuse methodist senior high/tech school', 'technical', NULL),
  ('AKWAMUMAN SENIOR HIGH SCHOOL', 'akwamuman senior high school', 'shs', NULL),
  ('AKWESI AWOBAA SENIOR HIGH SCHOOL', 'akwesi awobaa senior high school', 'shs', NULL),
  ('AKYIN SENIOR HIGH SCHOOL', 'akyin senior high school', 'shs', NULL),
  ('AL-AZARIYA ISLAMIC SENIOR HIGH SCHOOL, KUMASI', 'al-azariya islamic senior high school, kumasi', 'shs', NULL),
  ('ALAVANYO SENIOR HIGH/TECH SCHOOL', 'alavanyo senior high/tech school', 'technical', NULL),
  ('AMANIAMPONG SENIOR HIGH SCHOOL', 'amaniampong senior high school', 'shs', NULL),
  ('AMANTEN SENIOR HIGH SCHOOL', 'amanten senior high school', 'shs', NULL),
  ('AMASAMAN SENIOR HIGH/TECH SCHOOL', 'amasaman senior high/tech school', 'technical', NULL),
  ('AMENFIMAN SENIOR HIGH SCHOOL', 'amenfiman senior high school', 'shs', NULL),
  ('AMEYAW AKUMFI SENIOR HIGH/TECH SCHOOL', 'ameyaw akumfi senior high/tech school', 'technical', NULL),
  ('AMOANA PRASO SENIOR HIGH SCHOOL', 'amoana praso senior high school', 'shs', NULL),
  ('ANBARIYA SENIOR HIGH SCHOOL', 'anbariya senior high school', 'shs', NULL),
  ('ANFOEGA SENIOR HIGH SCHOOL', 'anfoega senior high school', 'shs', NULL),
  ('ANGLICAN SENIOR HIGH SCHOOL, KUMASI', 'anglican senior high school, kumasi', 'shs', NULL),
  ('ANLO AFIADENYIGBA SENIOR HIGH SCHOOL', 'anlo afiadenyigba senior high school', 'shs', NULL),
  ('ANLO AWOMEFIA SENIOR HIGH SCHOOL', 'anlo awomefia senior high school', 'shs', NULL),
  ('ANLO SENIOR HIGH SCHOOL', 'anlo senior high school', 'shs', NULL),
  ('ANNOR ADJAYE SENIOR HIGH SCHOOL', 'annor adjaye senior high school', 'shs', NULL),
  ('ANTOA SENIOR HIGH SCHOOL', 'antoa senior high school', 'shs', NULL),
  ('ANUM APAPAM COMM. DAY SENIOR HIGH SCHOOL', 'anum apapam comm day senior high school', 'shs', NULL)
ON CONFLICT (name_norm) DO NOTHING;

INSERT INTO senior_high_schools (name, name_norm, school_type, region)
VALUES
  ('ANUM PRESBY SENIOR HIGH SCHOOL', 'anum presby senior high school', 'shs', NULL),
  ('APAM SENIOR HIGH SCHOOL', 'apam senior high school', 'shs', NULL),
  ('APEDWA PRESBY SENIOR HIGH SCHOOL', 'apedwa presby senior high school', 'shs', NULL),
  ('APEGUSO SENIOR HIGH SCHOOL', 'apeguso senior high school', 'shs', NULL),
  ('APERADE SENIOR HIGH/TECH SCHOOL', 'aperade senior high/tech school', 'technical', NULL),
  ('ARCHBISHOP PORTER GIRLS SENIOR HIGH SCHOOL', 'archbishop porter girls senior high school', 'shs', NULL),
  ('ARMED FORCES SENIOR HIGH/TECH SCHOOL, KUMASI', 'armed forces senior high/tech school, kumasi', 'technical', NULL),
  ('ASAMANKESE SENIOR HIGH SCHOOL', 'asamankese senior high school', 'shs', NULL),
  ('ASANKRANGWA SENIOR HIGH SCHOOL', 'asankrangwa senior high school', 'shs', NULL),
  ('ASANKRANGWA SENIOR HIGH/TECH SCHOOL', 'asankrangwa senior high/tech school', 'technical', NULL),
  ('ASANTEMAN SENIOR HIGH SCHOOL', 'asanteman senior high school', 'shs', NULL),
  ('ASARE BEDIAKO SENIOR HIGH SCHOOL', 'asare bediako senior high school', 'shs', NULL),
  ('ASAWINSO SENIOR HIGH SCHOOL', 'asawinso senior high school', 'shs', NULL),
  ('ASESEWA SENIOR HIGH SCHOOL', 'asesewa senior high school', 'shs', NULL),
  ('ASHIAMAN SENIOR HIGH SCHOOL', 'ashiaman senior high school', 'shs', NULL),
  ('ASSIN MANSO SENIOR HIGH SCHOOL', 'assin manso senior high school', 'shs', NULL),
  ('ASSIN NORTH SENIOR HIGH/TECH SCHOOL', 'assin north senior high/tech school', 'technical', NULL),
  ('ASSIN NSUTA SENIOR HIGH SCHOOL', 'assin nsuta senior high school', 'shs', NULL),
  ('ASUKAWKAW SENIOR HIGH SCHOOL', 'asukawkaw senior high school', 'shs', NULL),
  ('ASUOM SENIOR HIGH SCHOOL', 'asuom senior high school', 'shs', NULL),
  ('ASUOSO COMM. SENIOR HIGH SCHOOL', 'asuoso comm senior high school', 'shs', NULL),
  ('ATEBUBU SENIOR HIGH SCHOOL', 'atebubu senior high school', 'shs', NULL),
  ('ATIAVI SENIOR HIGH/TECH SCHOOL', 'atiavi senior high/tech school', 'technical', NULL),
  ('ATTAFUAH SENIOR HIGH/TECH SCHOOL', 'attafuah senior high/tech school', 'technical', NULL),
  ('ATWEAMAN SENIOR HIGH SCHOOL', 'atweaman senior high school', 'shs', NULL),
  ('ATWIMA KWANWOMA SENIOR HIGH/TECH SCHOOL', 'atwima kwanwoma senior high/tech school', 'technical', NULL),
  ('AVATIME SENIOR HIGH SCHOOL', 'avatime senior high school', 'shs', NULL),
  ('AVE SENIOR HIGH SCHOOL', 'ave senior high school', 'shs', NULL),
  ('AVENOR SENIOR HIGH SCHOOL', 'avenor senior high school', 'shs', NULL),
  ('AVEYIME BATTOR SENIOR HIGH/TECH SCHOOL', 'aveyime battor senior high/tech school', 'technical', NULL),
  ('AWE SENIOR HIGH/TECH SCHOOL', 'awe senior high/tech school', 'technical', NULL),
  ('AWUDOME SENIOR HIGH SCHOOL', 'awudome senior high school', 'shs', NULL),
  ('AWUTU BAWJIASE COMM SENIOR HIGH SCHOOL', 'awutu bawjiase comm senior high school', 'shs', NULL),
  ('AWUTU WINTON SENIOR HIGH SCHOOL', 'awutu winton senior high school', 'shs', NULL),
  ('AXIM GIRLS SENIOR HIGH SCHOOL', 'axim girls senior high school', 'shs', NULL),
  ('AYANFURI SENIOR HIGH SCHOOL', 'ayanfuri senior high school', 'shs', NULL),
  ('AYIREBI SENIOR HIGH SCHOOL', 'ayirebi senior high school', 'shs', NULL),
  ('AZEEM-NAMOA SENIOR HIGH/TECH SCHOOL', 'azeem-namoa senior high/tech school', 'technical', NULL),
  ('BADU SENIOR HIGH/TECH SCHOOL', 'badu senior high/tech school', 'technical', NULL),
  ('BAGLO RIDGE SENIOR HIGH/TECH SCHOOL', 'baglo ridge senior high/tech school', 'technical', NULL),
  ('BAIDOO BONSOE SENIOR HIGH/TECH SCHOOL', 'baidoo bonsoe senior high/tech school', 'technical', NULL),
  ('BAMBOI COMM. SENIOR HIGH SCHOOL', 'bamboi comm senior high school', 'shs', NULL),
  ('BANDAMAN SENIOR HIGH SCHOOL', 'bandaman senior high school', 'shs', NULL),
  ('BANKA COMM. SENIOR HIGH SCHOOL', 'banka comm senior high school', 'shs', NULL),
  ('BANKOMAN SENIOR HIGH SCHOOL', 'bankoman senior high school', 'shs', NULL),
  ('BAREKESE SENIOR HIGH SCHOOL', 'barekese senior high school', 'shs', NULL),
  ('BASSA COMMUNITY SENIOR HIGH SCHOOL', 'bassa community senior high school', 'shs', NULL),
  ('BATTOR SENIOR HIGH SCHOOL', 'battor senior high school', 'shs', NULL),
  ('BAWKU SENIOR HIGH SCHOOL', 'bawku senior high school', 'shs', NULL),
  ('BAWKU SENIOR HIGH/TECH SCHOOL', 'bawku senior high/tech school', 'technical', NULL),
  ('BECHEM PRESBY SENIOR HIGH SCHOOL', 'bechem presby senior high school', 'shs', NULL),
  ('BENKUM SENIOR HIGH SCHOOL', 'benkum senior high school', 'shs', NULL),
  ('BENSO SENIOR HIGH/TECH SCHOOL', 'benso senior high/tech school', 'technical', NULL),
  ('BEPONG SENIOR HIGH SCHOOL', 'bepong senior high school', 'shs', NULL),
  ('BEPOSO SENIOR HIGH SCHOOL', 'beposo senior high school', 'shs', NULL),
  ('BEREKUM PRESBY SENIOR HIGH SCHOOL', 'berekum presby senior high school', 'shs', NULL),
  ('BEREKUM SENIOR HIGH SCHOOL', 'berekum senior high school', 'shs', NULL),
  ('BIA SENIOR HIGH/TECH SCHOOL', 'bia senior high/tech school', 'technical', NULL),
  ('BIAKOYE COMM. DAY SCHOOL', 'biakoye comm day school', 'shs', NULL),
  ('BIBIANI SENIOR HIGH/TECH SCHOOL', 'bibiani senior high/tech school', 'technical', NULL),
  ('BIMBILLA SENIOR HIGH SCHOOL', 'bimbilla senior high school', 'shs', NULL),
  ('BINDURI COMM. SENIOR HIGH SCHOOL', 'binduri comm senior high school', 'shs', NULL),
  ('BIRIFOH SENIOR HIGH SCHOOL', 'birifoh senior high school', 'shs', NULL),
  ('BISEASE SENIOR HIGH/COMM. SCHOOL', 'bisease senior high/comm school', 'shs', NULL),
  ('BOA-AMPONSEM SENIOR HIGH SCHOOL', 'boa-amponsem senior high school', 'shs', NULL),
  ('BOAKYE TROMO SENIOR HIGH/TECH SCHOOL', 'boakye tromo senior high/tech school', 'technical', NULL),
  ('BODI SENIOR HIGH SCHOOL', 'bodi senior high school', 'shs', NULL),
  ('BODOMASE SENIOR HIGH/TECH SCHOOL', 'bodomase senior high/tech school', 'technical', NULL),
  ('BODWESANGO SENIOR HIGH SCHOOL', 'bodwesango senior high school', 'shs', NULL),
  ('BOLE SENIOR HIGH SCHOOL', 'bole senior high school', 'shs', NULL),
  ('BOLGA GIRLS SENIOR HIGH SCHOOL', 'bolga girls senior high school', 'shs', NULL),
  ('BOLGA SHERIGU COMM. SENIOR HIGH SCHOOL', 'bolga sherigu comm senior high school', 'shs', NULL),
  ('BOLGATANGA SENIOR HIGH SCHOOL', 'bolgatanga senior high school', 'shs', NULL),
  ('BOMAA COMM. SENIOR HIGH SCHOOL', 'bomaa comm senior high school', 'shs', NULL),
  ('BOMPATA PRESBY SENIOR HIGH SCHOOL', 'bompata presby senior high school', 'shs', NULL),
  ('BOMPEH SENIOR HIGH./TECH SCHOOL', 'bompeh senior high/tech school', 'technical', NULL),
  ('BONGO SENIOR HIGH SCHOOL', 'bongo senior high school', 'shs', NULL),
  ('BONTRASE SENIOR HIGH TECH. SCHOOL', 'bontrase senior high tech school', 'technical', NULL),
  ('BONWIRE SENIOR HIGH/TECH SCHOOL', 'bonwire senior high/tech school', 'technical', NULL),
  ('BONZO-KAKU SENIOR HIGH SCHOOL', 'bonzo-kaku senior high school', 'shs', NULL)
ON CONFLICT (name_norm) DO NOTHING;

INSERT INTO senior_high_schools (name, name_norm, school_type, region)
VALUES
  ('BOSO SENIOR HIGH TECHNICAL SCHOOL', 'boso senior high technical school', 'technical', NULL),
  ('BOSOME SENIOR HIGH/TECH. SCHOOL', 'bosome senior high/tech school', 'technical', NULL),
  ('BOSOMTWE OYOKO COMM. SENIOR HIGH SCHOOL', 'bosomtwe oyoko comm senior high school', 'shs', NULL),
  ('BOWIRI COMM. DAY SCHOOL', 'bowiri comm day school', 'shs', NULL),
  ('BRAKWA SENIOR HIGH/TECH SCHOOL', 'brakwa senior high/tech school', 'technical', NULL),
  ('BREMAN ASIKUMA SENIOR HIGH SCHOOL', 'breman asikuma senior high school', 'shs', NULL),
  ('BUEMAN SENIOR HIGH SCHOOL', 'bueman senior high school', 'shs', NULL),
  ('BUIPE SENIOR HIGH SCHOOL', 'buipe senior high school', 'shs', NULL),
  ('BUNKPURUGU SENIOR HIGH/TECH SCHOOL', 'bunkpurugu senior high/tech school', 'technical', NULL),
  ('BUSINESS SENIOR HIGH SCHOOL, TAMALE', 'business senior high school, tamale', 'shs', NULL),
  ('BUSUNYA SENIOR HIGH SCHOOL', 'busunya senior high school', 'shs', NULL),
  ('CHEMU SENIOR HIGH/TECH SCHOOL', 'chemu senior high/tech school', 'technical', NULL),
  ('CHEREPONI SENIOR HIGH/TECH SCHOOL', 'chereponi senior high/tech school', 'technical', NULL),
  ('CHIANA SENIOR HIGH SCHOOL', 'chiana senior high school', 'shs', NULL),
  ('CHIRAA SENIOR HIGH SCHOOL', 'chiraa senior high school', 'shs', NULL),
  ('CHIRANO COMM. DAY SENIOR HIGH SCHOOL', 'chirano comm day senior high school', 'shs', NULL),
  ('CHRISTIAN METHODIST SENIOR HIGH SCHOOL', 'christian methodist senior high school', 'shs', NULL),
  ('CHURCH OF CHRIST SENIOR HIGH SCHOOL', 'church of christ senior high school', 'shs', NULL),
  ('COLLEGE OF MUSIC SENIOR HIGH SCHOOL, MOZANO', 'college of music senior high school, mozano', 'shs', NULL),
  ('COLLINS SENIOR HIGH/COMMERCIAL SCHOOL, AGOGO', 'collins senior high/commercial school, agogo', 'shs', NULL),
  ('DABOASE SENIOR HIGH/TECH SCHOOL', 'daboase senior high/tech school', 'technical', NULL),
  ('DABOYA COMM. DAY SCHOOL', 'daboya comm day school', 'shs', NULL),
  ('DADEASE AGRIC SENIOR HIGH SCHOOL', 'dadease agric senior high school', 'shs', NULL),
  ('DADIESO SENIOR HIGH SCHOOL', 'dadieso senior high school', 'shs', NULL),
  ('DAFFIAMAH SENIOR HIGH SCHOOL', 'daffiamah senior high school', 'shs', NULL),
  ('DAGBON STATE SENIOR HIGH/TECH SCHOOL', 'dagbon state senior high/tech school', 'technical', NULL),
  ('DAMONGO SENIOR HIGH SCHOOL', 'damongo senior high school', 'shs', NULL),
  ('DENYASEMAN CATH.SENIOR HIGH SCHOOL', 'denyaseman cathsenior high school', 'shs', NULL),
  ('DERMA COMM. DAY SENIOR HIGH SCHOOL', 'derma comm day senior high school', 'shs', NULL),
  ('DIABENE SENIOR HIGH/TECH SCHOOL', 'diabene senior high/tech school', 'technical', NULL),
  ('DIAMONO SENIOR HIGH SCHOOL', 'diamono senior high school', 'shs', NULL),
  ('DIASO SENIOR HIGH SCHOOL', 'diaso senior high school', 'shs', NULL),
  ('DIASPORA GIRLS'' SENIOR HIGH SCHOOL', 'diaspora girls senior high school', 'shs', NULL),
  ('DODI-PAPASE SENIOR HIGH/TECH SCHOOL', 'dodi-papase senior high/tech school', 'technical', NULL),
  ('DOFOR SENIOR HIGH SCHOOL', 'dofor senior high school', 'shs', NULL),
  ('DOMPOASE SENIOR HIGH SCHOOL', 'dompoase senior high school', 'shs', NULL),
  ('DONKORKROM AGRIC SENIOR HIGH SCHOOL', 'donkorkrom agric senior high school', 'shs', NULL),
  ('DORMAA SENIOR HIGH SCHOOL', 'dormaa senior high school', 'shs', NULL),
  ('DR. HILA LIMAN SENIOR HIGH SCHOOL', 'dr hila liman senior high school', 'shs', NULL),
  ('DROBO SENIOR HIGH SCHOOL', 'drobo senior high school', 'shs', NULL),
  ('DUADASO NO. 1 SENIOR HIGH/TECH SCHOOL', 'duadaso no 1 senior high/tech school', 'technical', NULL),
  ('DUNKWA SENIOR HIGH/TECH SCHOOL', 'dunkwa senior high/tech school', 'technical', NULL),
  ('DWAMENA AKENTEN SENIOR HIGH SCHOOL', 'dwamena akenten senior high school', 'shs', NULL),
  ('DZODZE PENYI SENIOR HIGH SCHOOL', 'dzodze penyi senior high school', 'shs', NULL),
  ('DZOLO SENIOR HIGH SCHOOL', 'dzolo senior high school', 'shs', NULL),
  ('E. P. AGRIC SENIOR HIGH/TECH SCHOOL', 'e p agric senior high/tech school', 'technical', NULL),
  ('E. P. SENIOR HIGH SCHOOL', 'e p senior high school', 'shs', NULL),
  ('EBENEZER SENIOR HIGH SCHOOL', 'ebenezer senior high school', 'shs', NULL),
  ('EDINAMAN SENIOR HIGH SCHOOL', 'edinaman senior high school', 'shs', NULL),
  ('EFFIDUASE SENIOR HIGH/COM SCHOOL', 'effiduase senior high/com school', 'shs', NULL),
  ('EFFIDUASE SENIOR HIGH/TECH SCHOOL', 'effiduase senior high/tech school', 'technical', NULL),
  ('EFFUTU SENIOR HIGH/TECH SCHOOL', 'effutu senior high/tech school', 'technical', NULL),
  ('EGUAFO-ABREM SENIOR HIGH SCHOOL', 'eguafo-abrem senior high school', 'shs', NULL),
  ('EJISU SENIOR HIGH/TECH SCHOOL', 'ejisu senior high/tech school', 'technical', NULL),
  ('EJISUMAN SENIOR HIGH SCHOOL', 'ejisuman senior high school', 'shs', NULL),
  ('EJURAMAN ANGLICAN SENIOR HIGH SCHOOL', 'ejuraman anglican senior high school', 'shs', NULL),
  ('EKUMFI T. I. AHMADIIYYA SENIOR HIGH SCHOOL', 'ekumfi t i ahmadiiyya senior high school', 'shs', NULL),
  ('ENYAN DENKYIRA SENIOR HIGH SCHOOL', 'enyan denkyira senior high school', 'shs', NULL),
  ('ENYAN MAIM COMM. DAY SENIOR HIGH SCHOOL', 'enyan maim comm day senior high school', 'shs', NULL),
  ('E.P.C. MAWUKO GIRLS SENIOR HIGH SCHOOL', 'epc mawuko girls senior high school', 'shs', NULL),
  ('EREMON SENIOR HIGH/TECH SCHOOL', 'eremon senior high/tech school', 'technical', NULL),
  ('ESAASE BONTEFUFUO SNR. HIGH/TECH. SCHOOL', 'esaase bontefufuo snr high/tech school', 'technical', NULL),
  ('ESIAMA SENIOR HIGH/TECH SCHOOL', 'esiama senior high/tech school', 'technical', NULL),
  ('FETTEHMAN SENIOR HIGH SCHOOL', 'fettehman senior high school', 'shs', NULL),
  ('FIASEMAN SENIOR HIGH SCHOOL', 'fiaseman senior high school', 'shs', NULL),
  ('FIJAI SENIOR HIGH SCHOOL', 'fijai senior high school', 'shs', NULL),
  ('FODOA COMM. SENIOR HIGH SCHOOL', 'fodoa comm senior high school', 'shs', NULL),
  ('FOMENA T.I. AHMAD SENIOR HIGH SCHOOL', 'fomena ti ahmad senior high school', 'shs', NULL),
  ('FORCES SENIOR HIGH/TECH SCHOOL, BURMA CAMP', 'forces senior high/tech school, burma camp', 'technical', NULL),
  ('FRAFRAHA COMM. SENIOR HIGH SCHOOL', 'frafraha comm senior high school', 'shs', NULL),
  ('FUMBISI SENIOR HIGH SCHOOL', 'fumbisi senior high school', 'shs', NULL),
  ('FUNSI SENIOR HIGH SCHOOL', 'funsi senior high school', 'shs', NULL),
  ('GAMBAGA GIRLS SENIOR HIGH SCHOOL', 'gambaga girls senior high school', 'shs', NULL),
  ('GAMBIGO COMM. DAY SENIOR HIGH SCHOOL', 'gambigo comm day senior high school', 'shs', NULL),
  ('GARU COMM. DAY SENIOR HIGH SCHOOL', 'garu comm day senior high school', 'shs', NULL),
  ('GHANA MUSLIM MISSION SENIOR HIGH SCHOOL', 'ghana muslim mission senior high school', 'shs', NULL),
  ('GHANA SENIOR HIGH SCHOOL, KOFORIDUA', 'ghana senior high school, koforidua', 'shs', NULL),
  ('GHANA SENIOR HIGH SCHOOL, TAMALE', 'ghana senior high school, tamale', 'shs', NULL),
  ('GHANA SENIOR HIGH/TECH SCHOOL', 'ghana senior high/tech school', 'technical', NULL),
  ('GHANATA SENIOR HIGH SCHOOL', 'ghanata senior high school', 'shs', NULL)
ON CONFLICT (name_norm) DO NOTHING;

INSERT INTO senior_high_schools (name, name_norm, school_type, region)
VALUES
  ('GOKA SENIOR HIGH/TECH SCHOOL', 'goka senior high/tech school', 'technical', NULL),
  ('GOMOA GYAMAN SENIOR HIGH SCHOOL', 'gomoa gyaman senior high school', 'shs', NULL),
  ('GOMOA SENIOR HIGH/TECH SCHOOL', 'gomoa senior high/tech school', 'technical', NULL),
  ('GOWRIE SENIOR HIGH/TECH SCHOOL', 'gowrie senior high/tech school', 'technical', NULL),
  ('GUAKRO EFFAH SENIOR HIGH SCHOOL', 'guakro effah senior high school', 'shs', NULL),
  ('GUSHEGU SENIOR HIGH SCHOOL', 'gushegu senior high school', 'shs', NULL),
  ('GWIRAMAN COMM.SENIOR HIGH SCHOOL', 'gwiraman commsenior high school', 'shs', NULL),
  ('GYAAMA PENSAN SENIOR HIGH/TECH SCHOOL', 'gyaama pensan senior high/tech school', 'technical', NULL),
  ('GYAASE COMMUNITY SENIOR HIGH SCHOOL', 'gyaase community senior high school', 'shs', NULL),
  ('GYAMFI KUMANINI SENIOR HIGH/TECH SCHOOL', 'gyamfi kumanini senior high/tech school', 'technical', NULL),
  ('GYARKO COMM. DAY SENIOR HIGH SCHOOL', 'gyarko comm day senior high school', 'shs', NULL),
  ('HALF ASSINI SENIOR HIGH SCHOOL', 'half assini senior high school', 'shs', NULL),
  ('HAN SENIOR HIGH SCHOOL', 'han senior high school', 'shs', NULL),
  ('H''MOUNT SINAI SENIOR HIGH SCHOOL', 'hmount sinai senior high school', 'shs', NULL),
  ('HOLY CHILD SCHOOL, CAPE COAST', 'holy child school, cape coast', 'shs', NULL),
  ('HOLY FAMILY SENIOR HIGH SCHOOL', 'holy family senior high school', 'shs', NULL),
  ('HOLY TRINITY SENIOR HIGH SCHOOL', 'holy trinity senior high school', 'shs', NULL),
  ('HUNI VALLEY SENIOR HIGH SCHOOL', 'huni valley senior high school', 'shs', NULL),
  ('HWIDIEM SENIOR HIGH SCHOOL', 'hwidiem senior high school', 'shs', NULL),
  ('ISLAMIC GIRLS SENIOR HIGH SCHOOL,SUHUM', 'islamic girls senior high school,suhum', 'shs', NULL),
  ('ISLAMIC SCIENCE SENIOR HIGH SCHOOL, TAMALE', 'islamic science senior high school, tamale', 'shs', NULL),
  ('ISLAMIC SENIOR HIGH SCHOOL, AMPABAME', 'islamic senior high school, ampabame', 'shs', NULL),
  ('ISLAMIC SENIOR HIGH SCHOOL, WA', 'islamic senior high school, wa', 'shs', NULL),
  ('ISTIQUAAMA SENIOR HIGH SCHOOL', 'istiquaama senior high school', 'shs', NULL),
  ('JACHIE PRAMSO SENIOR HIGH SCHOOL', 'jachie pramso senior high school', 'shs', NULL),
  ('JACOBU SENIOR HIGH/TECH. SCHOOL', 'jacobu senior high/tech school', 'technical', NULL),
  ('JAMIAT AL-HIDAYA ISLAMIC GIRLS SENIOR HIGH SCHOOL', 'jamiat al-hidaya islamic girls senior high school', 'shs', NULL),
  ('JANGA SENIOR HIGH/TECH SCHOOL', 'janga senior high/tech school', 'technical', NULL),
  ('J.E.A. MILLS SENIOR HIGH SCHOOL', 'jea mills senior high school', 'shs', NULL),
  ('JEMA SENIOR HIGH SCHOOL', 'jema senior high school', 'shs', NULL),
  ('JIM BOURTON MEM AGRIC. SENIOR HIGH SCHOOL', 'jim bourton mem agric senior high school', 'shs', NULL),
  ('JINIJINI SENIOR HIGH SCHOOL', 'jinijini senior high school', 'shs', NULL),
  ('JIRAPA SENIOR HIGH SCHOOL', 'jirapa senior high school', 'shs', NULL),
  ('JUABEN SENIOR HIGH SCHOOL', 'juaben senior high school', 'shs', NULL),
  ('JUABOSO SENIOR HIGH SCHOOL', 'juaboso senior high school', 'shs', NULL),
  ('JUASO SENIOR HIGH/TECH SCHOOL', 'juaso senior high/tech school', 'technical', NULL),
  ('JUBILEE SENIOR HIGH SCHOOL', 'jubilee senior high school', 'shs', NULL),
  ('JUKWA SENIOR HIGH SCHOOL', 'jukwa senior high school', 'shs', NULL),
  ('KADE SENIOR HIGH/TECH SCHOOL', 'kade senior high/tech school', 'technical', NULL),
  ('KADJEBI-ASATO SENIOR HIGH SCHOOL', 'kadjebi-asato senior high school', 'shs', NULL),
  ('KAJAJI SENIOR HIGH SCHOOL', 'kajaji senior high school', 'shs', NULL),
  ('KALEO SENIOR HIGH/TECH SCHOOL', 'kaleo senior high/tech school', 'technical', NULL),
  ('KALPOHIN SENIOR HIGH SCHOOL', 'kalpohin senior high school', 'shs', NULL),
  ('KANESHIE SENIOR HIGH/TECH SCHOOL', 'kaneshie senior high/tech school', 'technical', NULL),
  ('KANJAGA COMM. SENIOR HIGH SCHOOL', 'kanjaga comm senior high school', 'shs', NULL),
  ('KANTON SENIOR HIGH SCHOOL', 'kanton senior high school', 'shs', NULL),
  ('KARAGA SENIOR HIGH SCHOOL', 'karaga senior high school', 'shs', NULL),
  ('KASULIYILI SENIOR HIGH SCHOOL', 'kasuliyili senior high school', 'shs', NULL),
  ('KESSE BASAHYIA SENIOR HIGH SCHOOL', 'kesse basahyia senior high school', 'shs', NULL),
  ('KETA BUSINESS SENIOR HIGH SCHOOL', 'keta business senior high school', 'shs', NULL),
  ('KETA SENIOR HIGH/TECH SCHOOL', 'keta senior high/tech school', 'technical', NULL),
  ('KETE KRACHI SENIOR HIGH/TECH SCHOOL', 'kete krachi senior high/tech school', 'technical', NULL),
  ('KIBI SENIOR HIGH/TECH SCHOOL', 'kibi senior high/tech school', 'technical', NULL),
  ('KINBU SENIOR HIGH/TECH SCHOOL', 'kinbu senior high/tech school', 'technical', NULL),
  ('KINTAMPO SENIOR HIGH SCHOOL', 'kintampo senior high school', 'shs', NULL),
  ('KLIKOR SENIOR HIGH/TECH SCHOOL', 'klikor senior high/tech school', 'technical', NULL),
  ('KLO-AGOGO SENIOR HIGH SCHOOL', 'klo-agogo senior high school', 'shs', NULL),
  ('KNUST SENIOR HIGH SCHOOL', 'knust senior high school', 'shs', NULL),
  ('KO SENIOR HIGH SCHOOL', 'ko senior high school', 'shs', NULL),
  ('KOASE SENIOR HIGH/TECH SCHOOL', 'koase senior high/tech school', 'technical', NULL),
  ('KOFI ADJEI SENIOR HIGH/TECH SCHOOL', 'kofi adjei senior high/tech school', 'technical', NULL),
  ('KOFIASE ADVENTIST SENIOR HIGH/TECH. SCHOOL', 'kofiase adventist senior high/tech school', 'technical', NULL),
  ('KOFORIDUA SENIOR HIGH/TECH SCHOOL', 'koforidua senior high/tech school', 'technical', NULL),
  ('KOMENDA SENIOR HIGH/TECH SCHOOL', 'komenda senior high/tech school', 'technical', NULL),
  ('KONADU YIADOM CATHOLIC SENIOR HIGH SCHOOL', 'konadu yiadom catholic senior high school', 'shs', NULL),
  ('KONGO SENIOR HIGH SCHOOL', 'kongo senior high school', 'shs', NULL),
  ('KONONGO ODUMASE SENIOR HIGH SCHOOL', 'konongo odumase senior high school', 'shs', NULL),
  ('KPANDAI SENIOR HIGH SCHOOL', 'kpandai senior high school', 'shs', NULL),
  ('KPANDO SENIOR HIGH SCHOOL', 'kpando senior high school', 'shs', NULL),
  ('KPASSA SENIOR HIGH/TECH SCHOOL', 'kpassa senior high/tech school', 'technical', NULL),
  ('KPEDZE SENIOR HIGH SCHOOL', 'kpedze senior high school', 'shs', NULL),
  ('KPEVE SENIOR HIGH SCHOOL', 'kpeve senior high school', 'shs', NULL),
  ('KPONE COMM. SENIOR HIGH SCHOOL', 'kpone comm senior high school', 'shs', NULL),
  ('KRABOA-COALTAR PRESBY SENIOR HIGH SCHOOL HIGH/TECH.', 'kraboa-coaltar presby senior high school high/tech', 'technical', NULL),
  ('KRACHI SENIOR HIGH SCHOOL', 'krachi senior high school', 'shs', NULL),
  ('KROBEA ASANTE TECH/VOC SCHOOL', 'krobea asante tech/voc school', 'technical', NULL),
  ('KROBO COMM.SENIOR HIGH SCHOOL', 'krobo commsenior high school', 'shs', NULL),
  ('KROBO GIRLS SENIOR HIGH SCHOOL', 'krobo girls senior high school', 'shs', NULL),
  ('KUKUOM AGRIC SENIOR HIGH SCHOOL', 'kukuom agric senior high school', 'shs', NULL),
  ('KUMASI GIRLS SENIOR HIGH SCHOOL', 'kumasi girls senior high school', 'shs', NULL)
ON CONFLICT (name_norm) DO NOTHING;

INSERT INTO senior_high_schools (name, name_norm, school_type, region)
VALUES
  ('KUMASI SENIOR HIGH SCHOOL', 'kumasi senior high school', 'shs', NULL),
  ('KUMASI SENIOR HIGH/TECH SCHOOL', 'kumasi senior high/tech school', 'technical', NULL),
  ('KUMASI WESLEY GIRLS HIGH SCHOOL', 'kumasi wesley girls high school', 'shs', NULL),
  ('KUMBUNGU SENIOR HIGH SCHOOL', 'kumbungu senior high school', 'shs', NULL),
  ('KUROFA METHODIST SENIOR HIGH SCHOOL', 'kurofa methodist senior high school', 'shs', NULL),
  ('KUSANABA SENIOR HIGH SCHOOL', 'kusanaba senior high school', 'shs', NULL),
  ('KWABENG ANGLICAN SENIOR HIGH/TECH SCHOOL', 'kwabeng anglican senior high/tech school', 'technical', NULL),
  ('KWABENYA COMM. SENIOR HIGH SCHOOL', 'kwabenya comm senior high school', 'shs', NULL),
  ('KWABRE SENIOR HIGH SCHOOL', 'kwabre senior high school', 'shs', NULL),
  ('KWAHU RIDGE SENIOR HIGH SCHOOL', 'kwahu ridge senior high school', 'shs', NULL),
  ('KWAHU TAFO SENIOR HIGH SCHOOL', 'kwahu tafo senior high school', 'shs', NULL),
  ('KWAME DANSO SENIOR HIGH/TECH SCHOOL', 'kwame danso senior high/tech school', 'technical', NULL),
  ('KWANWOMA SENIOR HIGH SCHOOL', 'kwanwoma senior high school', 'shs', NULL),
  ('KWANYAKO SENIOR HIGH SCHOOL', 'kwanyako senior high school', 'shs', NULL),
  ('KWAOBAAH NYANOA COMM. SENIOR HIGH SCHOOL', 'kwaobaah nyanoa comm senior high school', 'shs', NULL),
  ('KWARTENG ANKOMAH SENIOR HIGH SCHOOL', 'kwarteng ankomah senior high school', 'shs', NULL),
  ('KWEGYIR AGGREY SENIOR HIGH SCHOOL', 'kwegyir aggrey senior high school', 'shs', NULL),
  ('KYABOBO GIRLS SENIOR HIGH SCHOOL', 'kyabobo girls senior high school', 'shs', NULL),
  ('LA PRESBY SENIOR HIGH SCHOOL', 'la presby senior high school', 'shs', NULL),
  ('LABONE SENIOR HIGH SCHOOL', 'labone senior high school', 'shs', NULL),
  ('LAMBUSSIE COMM SENIOR HIGH SCHOOL', 'lambussie comm senior high school', 'shs', NULL),
  ('LANGBINSI SENIOR HIGH TECHNICAL SCHOOL', 'langbinsi senior high technical school', 'technical', NULL),
  ('LASHIBI COMMUNITY SENIOR HIGH SCHOOL', 'lashibi community senior high school', 'shs', NULL),
  ('LASSIE-TUOLU SENIOR HIGH SCHOOL', 'lassie-tuolu senior high school', 'shs', NULL),
  ('LAWRA SENIOR HIGH SCHOOL', 'lawra senior high school', 'shs', NULL),
  ('LEKLEBI SENIOR HIGH SCHOOL', 'leklebi senior high school', 'shs', NULL),
  ('LIKPE SENIOR HIGH SCHOOL', 'likpe senior high school', 'shs', NULL),
  ('LOGGU COMM. DAY SCHOOL', 'loggu comm day school', 'shs', NULL),
  ('MAABANG SENIOR HIGH/TECH SCHOOL', 'maabang senior high/tech school', 'technical', NULL),
  ('MAAME KROBO COMM. SENIOR HIGH SCHOOL', 'maame krobo comm senior high school', 'shs', NULL),
  ('MAFI-KUMASI SENIOR HIGH/TECH SCHOOL', 'mafi-kumasi senior high/tech school', 'technical', NULL),
  ('MAMPONG/AKW SENIOR HIGH/TECH SCHOOL FOR THE DEAF', 'mampong/akw senior high/tech school for the deaf', 'technical', NULL),
  ('MANDO SENIOR HIGH/TECH SCHOOL', 'mando senior high/tech school', 'technical', NULL),
  ('MANGOASE SENIOR HIGH SCHOOL', 'mangoase senior high school', 'shs', NULL),
  ('MANKESSIM SENIOR HIGH/TECH SCHOOL', 'mankessim senior high/tech school', 'technical', NULL),
  ('MANKRANSO SENIOR HIGH SCHOOL', 'mankranso senior high school', 'shs', NULL),
  ('MANSEN SENIOR HIGH SCHOOL', 'mansen senior high school', 'shs', NULL),
  ('MANSO-ADUBIA SENIOR HIGH SCHOOL', 'manso-adubia senior high school', 'shs', NULL),
  ('MANSO-AMENFI COMM. DAY SENIOR HIGH SCHOOL', 'manso-amenfi comm day senior high school', 'shs', NULL),
  ('MANSOMAN SENIOR HIGH SCHOOL', 'mansoman senior high school', 'shs', NULL),
  ('MANYA KROBO SENIOR HIGH SCHOOL', 'manya krobo senior high school', 'shs', NULL),
  ('MAWULI SCHOOL, HO', 'mawuli school, ho', 'shs', NULL),
  ('MEM-CHEMFRE COMM. SENIOR HIGH SCHOOL', 'mem-chemfre comm senior high school', 'shs', NULL),
  ('MENJI SENIOR HIGH SCHOOL', 'menji senior high school', 'shs', NULL),
  ('MEPE ST. KIZITO SENIOR HIGH/TECH SCHOOL', 'mepe st kizito senior high/tech school', 'technical', NULL),
  ('METHODIST GIRLS SENIOR HIGH SCHOOL, MAMFE', 'methodist girls senior high school, mamfe', 'shs', NULL),
  ('METHODIST HIGH SCHOOL,SALTPOND', 'methodist high school,saltpond', 'shs', NULL),
  ('METHODIST SENIOR HIGH SCHOOL, SEKONDI', 'methodist senior high school, sekondi', 'shs', NULL),
  ('METHODIST SENIOR HIGH/TECH SCHOOL,BIADAN', 'methodist senior high/tech school,biadan', 'technical', NULL),
  ('MFANTSIMAN GIRLS SENIOR HIGH SCHOOL', 'mfantsiman girls senior high school', 'shs', NULL),
  ('MFANTSIPIM SCHOOL', 'mfantsipim school', 'shs', NULL),
  ('MIM SENIOR HIGH SCHOOL', 'mim senior high school', 'shs', NULL),
  ('MIRIGU COMMUNITY DAY SENIOR HIGH SCHOOL', 'mirigu community day senior high school', 'shs', NULL),
  ('MOKWAA SENIOR HIGH SCHOOL', 'mokwaa senior high school', 'shs', NULL),
  ('MOREE COMM. SENIOR HIGH SCHOOL', 'moree comm senior high school', 'shs', NULL),
  ('MOZANO SENIOR HIGH SCHOOL', 'mozano senior high school', 'shs', NULL),
  ('MPAHA COMMUNITY DAY SENIOR HIGH SCHOOL', 'mpaha community day senior high school', 'shs', NULL),
  ('MPASATIA SENIOR HIGH/TECH SCHOOL', 'mpasatia senior high/tech school', 'technical', NULL),
  ('MPOHOR SENIOR HIGH SCHOOL', 'mpohor senior high school', 'shs', NULL),
  ('MPRAESO SENIOR HIGH SCHOOL', 'mpraeso senior high school', 'shs', NULL),
  ('NABANGO SENIOR HIGH SCHOOL', 'nabango senior high school', 'shs', NULL),
  ('NAFANA SENIOR HIGH SCHOOL', 'nafana senior high school', 'shs', NULL),
  ('NAKPANDURI SENIOR HIGH SCHOOL', 'nakpanduri senior high school', 'shs', NULL),
  ('NALERIGU SENIOR HIGH SCHOOL', 'nalerigu senior high school', 'shs', NULL),
  ('NAMONG SENIOR HIGH/TECH SCHOOL', 'namong senior high/tech school', 'technical', NULL),
  ('NANA BRENTU SENIOR HIGH/TECH SCHOOL', 'nana brentu senior high/tech school', 'technical', NULL),
  ('NANDOM SENIOR HIGH SCHOOL', 'nandom senior high school', 'shs', NULL),
  ('NAVRONGO SENIOR HIGH SCHOOL', 'navrongo senior high school', 'shs', NULL),
  ('NCHUMURUMAN COMM. DAY SENIOR HIGH SCHOOL', 'nchumuruman comm day senior high school', 'shs', NULL),
  ('NDEWURA JAKPA SENIOR HIGH/TECH SCHOOL', 'ndewura jakpa senior high/tech school', 'technical', NULL),
  ('NEW ABIREM/AFOSU SENIOR HIGH SCHOOL', 'new abirem/afosu senior high school', 'shs', NULL),
  ('NEW EDUBIASE SENIOR HIGH SCHOOL', 'new edubiase senior high school', 'shs', NULL),
  ('NEW JUABEN SENIOR HIGH/COMM SCHOOL', 'new juaben senior high/comm school', 'shs', NULL),
  ('NEW KROKOMPE COMM. SENIOR HIGH SCHOOL', 'new krokompe comm senior high school', 'shs', NULL),
  ('NEW LONGORO COMM SENIOR HIGH SCHOOL (DEGA)', 'new longoro comm senior high school (dega)', 'shs', NULL),
  ('NEW NSUTAM SENIOR HIGH/TECH SCHOOL', 'new nsutam senior high/tech school', 'technical', NULL),
  ('NGLESHIE AMANFRO SENIOR HIGH SCHOOL', 'ngleshie amanfro senior high school', 'shs', NULL),
  ('NIFA SENIOR HIGH SCHOOL', 'nifa senior high school', 'shs', NULL),
  ('NINGO SENIOR HIGH SCHOOL', 'ningo senior high school', 'shs', NULL),
  ('NKAWIE SENIOR HIGH/TECH SCHOOL', 'nkawie senior high/tech school', 'technical', NULL)
ON CONFLICT (name_norm) DO NOTHING;

INSERT INTO senior_high_schools (name, name_norm, school_type, region)
VALUES
  ('NKAWKAW SENIOR HIGH SCHOOL', 'nkawkaw senior high school', 'shs', NULL),
  ('NKENKANSU COMMUNITY SENIOR HIGH SCHOOL', 'nkenkansu community senior high school', 'shs', NULL),
  ('NKONYA SENIOR HIGH SCHOOL', 'nkonya senior high school', 'shs', NULL),
  ('NKORANMAN SENIOR HIGH SCHOOL', 'nkoranman senior high school', 'shs', NULL),
  ('NKORANZA SENIOR HIGH/TECH SCHOOL', 'nkoranza senior high/tech school', 'technical', NULL),
  ('NKRANKWANTA COMM SENIOR HIGH SCHOOL', 'nkrankwanta comm senior high school', 'shs', NULL),
  ('NKROFUL AGRIC. SENIOR HIGH SCHOOL', 'nkroful agric senior high school', 'shs', NULL),
  ('NKWANTA COMM SENIOR HIGH SCHOOL', 'nkwanta comm senior high school', 'shs', NULL),
  ('NKWANTA SENIOR HIGH SCHOOL', 'nkwanta senior high school', 'shs', NULL),
  ('NKWATIA PRESBY SENIOR HIGH/COMM SCHOOL', 'nkwatia presby senior high/comm school', 'shs', NULL),
  ('NKYERAA SENIOR HIGH SCHOOL', 'nkyeraa senior high school', 'shs', NULL),
  ('NORTHERN SCHOOL OF BUSINESS', 'northern school of business', 'shs', NULL),
  ('NORTHERN STAR SENIOR HIGH SCHOOL', 'northern star senior high school', 'shs', NULL),
  ('NOTRE DAME GIRLS SENIOR HIGH SCHOOL, SUNYANI', 'notre dame girls senior high school, sunyani', 'shs', NULL),
  ('NOTRE DAME SEM/ SENIOR HIGH SCHOOL NAVRONGO', 'notre dame sem/ senior high school navrongo', 'shs', NULL),
  ('NSABA PRESBY SENIOR HIGH SCHOOL', 'nsaba presby senior high school', 'shs', NULL),
  ('NSAWAM SENIOR HIGH SCHOOL', 'nsawam senior high school', 'shs', NULL),
  ('NSAWKAW STATE SENIOR HIGH SCHOOL', 'nsawkaw state senior high school', 'shs', NULL),
  ('NSAWORA EDUMAFA COMM. SENIOR HIGH SCHOOL', 'nsawora edumafa comm senior high school', 'shs', NULL),
  ('NSEIN SENIOR HIGH SCHOOL', 'nsein senior high school', 'shs', NULL),
  ('NSUTAMAN CATH. SENIOR HIGH SCHOOL', 'nsutaman cath senior high school', 'shs', NULL),
  ('NTRUBOMAN SENIOR HIGH SCHOOL', 'ntruboman senior high school', 'shs', NULL),
  ('NUNGUA SENIOR HIGH SCHOOL', 'nungua senior high school', 'shs', NULL),
  ('NURU-AMEEN ISLAMIC SENIOR HIGH SCHOOL, ASEWASE', 'nuru-ameen islamic senior high school, asewase', 'shs', NULL),
  ('NYAKROM SENIOR HIGH TECH SCHOOL', 'nyakrom senior high tech school', 'technical', NULL),
  ('NYANKUMASE AHENKRO SENIOR HIGH SCHOOL', 'nyankumase ahenkro senior high school', 'shs', NULL),
  ('NYINAHIN CATH. SENIOR HIGH SCHOOL', 'nyinahin cath senior high school', 'shs', NULL),
  ('OBIRI YEBOAH SENIOR HIGH/TECHNICAL SCHOOL', 'obiri yeboah senior high/technical school', 'technical', NULL),
  ('OBRACHIRE SENIOR HIGH/TECH SCHOOL', 'obrachire senior high/tech school', 'technical', NULL),
  ('OBUASI SENIOR HIGH/TECH SCHOOL', 'obuasi senior high/tech school', 'technical', NULL),
  ('ODA SENIOR HIGH SCHOOL', 'oda senior high school', 'shs', NULL),
  ('ODOBEN SENIOR HIGH SCHOOL', 'odoben senior high school', 'shs', NULL),
  ('ODOMASEMAN SENIOR HIGH SCHOOL', 'odomaseman senior high school', 'shs', NULL),
  ('ODORGONNO SENIOR HIGH SCHOOL', 'odorgonno senior high school', 'shs', NULL),
  ('ODUPONG COMM. DAY SCHOOL', 'odupong comm day school', 'shs', NULL),
  ('OFOASE KOKOBEN SENIOR HIGH SCHOOL', 'ofoase kokoben senior high school', 'shs', NULL),
  ('OFOASE SENIOR HIGH/TECH SCHOOL', 'ofoase senior high/tech school', 'technical', NULL),
  ('OFORI PANIN SENIOR HIGH SCHOOL', 'ofori panin senior high school', 'shs', NULL),
  ('OGUAA SENIOR HIGH/TECH SCHOOL', 'oguaa senior high/tech school', 'technical', NULL),
  ('OGYEEDOM COMM SENIOR HIGH/TECH SCHOOL', 'ogyeedom comm senior high/tech school', 'technical', NULL),
  ('OKADJAKROM SENIOR HIGH/TECH SCHOOL', 'okadjakrom senior high/tech school', 'technical', NULL),
  ('OKOMFO ANOKYE SENIOR HIGH SCHOOL', 'okomfo anokye senior high school', 'shs', NULL),
  ('OKUAPEMAN SENIOR HIGH SCHOOL', 'okuapeman senior high school', 'shs', NULL),
  ('OLA GIRLS SENIOR HIGH SCHOOL, HO', 'ola girls senior high school, ho', 'shs', NULL),
  ('OLA GIRLS SENIOR HIGH SCHOOL, KENYASI', 'ola girls senior high school, kenyasi', 'shs', NULL),
  ('O.L.L. GIRLS SENIOR HIGH SCHOOL', 'oll girls senior high school', 'shs', NULL),
  ('ONWE SENIOR HIGH SCHOOL', 'onwe senior high school', 'shs', NULL),
  ('OPOKU AGYEMAN SENIOR HIGH/TECH SCHOOL', 'opoku agyeman senior high/tech school', 'technical', NULL),
  ('OPOKU WARE SENIOR HIGH SCHOOL', 'opoku ware senior high school', 'shs', NULL),
  ('OPPONG MEM. SENIOR HIGH SCHOOL', 'oppong mem senior high school', 'shs', NULL),
  ('O''REILLY SENIOR HIGH SCHOOL', 'oreilly senior high school', 'shs', NULL),
  ('OSEI ADUTWUM SENIOR HIGH SCHOOL', 'osei adutwum senior high school', 'shs', NULL),
  ('OSEI BONSU SENIOR HIGH SCHOOL', 'osei bonsu senior high school', 'shs', NULL),
  ('OSEI KYERETWIE SENIOR HIGH SCHOOL', 'osei kyeretwie senior high school', 'shs', NULL),
  ('OSEI TUTU SENIOR HIGH SCHOOL, AKROPONG', 'osei tutu senior high school, akropong', 'shs', NULL),
  ('OSINO PRESBY SENIOR HIGH/TECH SCHOOL', 'osino presby senior high/tech school', 'technical', NULL),
  ('OSUDOKU SENIOR HIGH/TECH SCHOOL', 'osudoku senior high/tech school', 'technical', NULL),
  ('OTI BOATENG SENIOR HIGH SCHOOL', 'oti boateng senior high school', 'shs', NULL),
  ('OTI SENIOR HIGH/TECH SCHOOL', 'oti senior high/tech school', 'technical', NULL),
  ('OUR LADY OF MERCY SENIOR HIGH SCHOOL', 'our lady of mercy senior high school', 'shs', NULL),
  ('OUR LADY OF MOUNT CARMEL GIRLS SENIOR HIGH SCHOOL, TECHIMAN', 'our lady of mount carmel girls senior high school, techiman', 'shs', NULL),
  ('OUR LADY OF PROVIDENCE SENIOR HIGH SCHOOL', 'our lady of providence senior high school', 'shs', NULL),
  ('OWERRIMAN SENIOR HIGH SCHOOL', 'owerriman senior high school', 'shs', NULL),
  ('OYOKO METHODIST SENIOR HIGH SCHOOL', 'oyoko methodist senior high school', 'shs', NULL),
  ('PAGA SENIOR HIGH SCHOOL', 'paga senior high school', 'shs', NULL),
  ('PARKOSO COMM. SENIOR HIGH SCHOOL', 'parkoso comm senior high school', 'shs', NULL),
  ('PEKI SENIOR HIGH SCHOOL', 'peki senior high school', 'shs', NULL),
  ('PEKI SENIOR HIGH/TECHNICAL SCHOOL', 'peki senior high/technical school', 'technical', NULL),
  ('PENTECOST SENIOR HIGH SCHOOL, KUMASI', 'pentecost senior high school, kumasi', 'shs', NULL),
  ('PENTECOST SENIOR HIGH SCHOOL,KOFORIDUA', 'pentecost senior high school,koforidua', 'shs', NULL),
  ('PIINA SENIOR HIGH SCHOOL', 'piina senior high school', 'shs', NULL),
  ('PONG-TAMALE SENIOR HIGH SCHOOL', 'pong-tamale senior high school', 'shs', NULL),
  ('POPE JOHN SENIOR HIGH & MIN. SEM. SCHOOL, KOFORIDUA', 'pope john senior high & min sem school, koforidua', 'shs', NULL),
  ('POTSIN T.I. AHM. SENIOR HIGH SCHOOL', 'potsin ti ahm senior high school', 'shs', NULL),
  ('PRAMPRAM SENIOR HIGH SCHOOL', 'prampram senior high school', 'shs', NULL),
  ('PRESBY BOYS SENIOR HIGH SCHOOL, LEGON', 'presby boys senior high school, legon', 'shs', NULL),
  ('PRESBY SENIOR HIGH SCHOOL, BEGORO', 'presby senior high school, begoro', 'shs', NULL),
  ('PRESBY SENIOR HIGH SCHOOL, MAMPONG AKWAPIM', 'presby senior high school, mampong akwapim', 'shs', NULL),
  ('PRESBY SENIOR HIGH SCHOOL, OSU', 'presby senior high school, osu', 'shs', NULL),
  ('PRESBY SENIOR HIGH SCHOOL, SUHUM', 'presby senior high school, suhum', 'shs', NULL)
ON CONFLICT (name_norm) DO NOTHING;

INSERT INTO senior_high_schools (name, name_norm, school_type, region)
VALUES
  ('PRESBY SENIOR HIGH SCHOOL, TAMALE', 'presby senior high school, tamale', 'shs', NULL),
  ('PRESBY SENIOR HIGH SCHOOL, TEMA', 'presby senior high school, tema', 'shs', NULL),
  ('PRESBY SENIOR HIGH SCHOOL, TESHIE', 'presby senior high school, teshie', 'shs', NULL),
  ('PRESBY SENIOR HIGH/TECH SCHOOL, ABURI', 'presby senior high/tech school, aburi', 'technical', NULL),
  ('PRESBY SENIOR HIGH/TECH SCHOOL, ADUKROM', 'presby senior high/tech school, adukrom', 'technical', NULL),
  ('PRESBY SENIOR HIGH/TECH SCHOOL, KWAMANG', 'presby senior high/tech school, kwamang', 'technical', NULL),
  ('PRESBY SENIOR HIGH/TECH SCHOOL, LARTEH', 'presby senior high/tech school, larteh', 'technical', NULL),
  ('PRESTEA SENIOR HIGH/TECH SCHOOL', 'prestea senior high/tech school', 'technical', NULL),
  ('QUEEN OF PEACE SENIOR HIGH SCHOOL, NADOWLI', 'queen of peace senior high school, nadowli', 'shs', NULL),
  ('QUEENS GIRLS'' SENIOR HIGH SCHOOL, SEFWI AWHIASO', 'queens girls senior high school, sefwi awhiaso', 'shs', NULL),
  ('SABOBA E.P. SENIOR HIGH SCHOOL', 'saboba ep senior high school', 'shs', NULL),
  ('SABRONUM METHODIST SENIOR HIGH/TECH SCHOOL', 'sabronum methodist senior high/tech school', 'technical', NULL),
  ('SACRED HEART SENIOR HIGH SCHOOL, NSOATRE', 'sacred heart senior high school, nsoatre', 'shs', NULL),
  ('SAKAFIA ISLAMIC SENIOR HIGH SCHOOL', 'sakafia islamic senior high school', 'shs', NULL),
  ('SAKOGU SENIOR HIGH/TECH SCHOOL', 'sakogu senior high/tech school', 'technical', NULL),
  ('SALAGA SENIOR HIGH SCHOOL', 'salaga senior high school', 'shs', NULL),
  ('SALAGA T.I. AHMAD SENIOR HIGH SCHOOL', 'salaga ti ahmad senior high school', 'shs', NULL),
  ('SALVATION ARMY SENIOR HIGH SCHOOL, ABOABO DORMAA', 'salvation army senior high school, aboabo dormaa', 'shs', NULL),
  ('SALVATION ARMY SENIOR HIGH SCHOOL, AKIM WENCHI', 'salvation army senior high school, akim wenchi', 'shs', NULL),
  ('SAMUEL OTU PRESBY SENIOR HIGH SCHOOL', 'samuel otu presby senior high school', 'shs', NULL),
  ('SANDEMA SENIOR HIGH SCHOOL', 'sandema senior high school', 'shs', NULL),
  ('SANDEMA SENIOR HIGH/TECH SCHOOL', 'sandema senior high/tech school', 'technical', NULL),
  ('SANG COMM. DAY SCHOOL', 'sang comm day school', 'shs', NULL),
  ('SANKOR COMM. DAY SENIOR HIGH SCHOOL', 'sankor comm day senior high school', 'shs', NULL),
  ('SANKORE SENIOR HIGH SCHOOL', 'sankore senior high school', 'shs', NULL),
  ('SAVELUGU SENIOR HIGH SCHOOL', 'savelugu senior high school', 'shs', NULL),
  ('SAVIOUR SENIOR HIGH SCHOOL, OSIEM', 'saviour senior high school, osiem', 'shs', NULL),
  ('SAWLA SENIOR HIGH SCHOOL', 'sawla senior high school', 'shs', NULL),
  ('S.D.A. SENIOR HIGH SCHOOL, AGONA', 'sda senior high school, agona', 'shs', NULL),
  ('S.D.A. SENIOR HIGH SCHOOL, BEKWAI', 'sda senior high school, bekwai', 'shs', NULL),
  ('S.D.A SENIOR HIGH SCHOOL, KOFORIDUA', 'sda senior high school, koforidua', 'shs', NULL),
  ('S.D.A SENIOR HIGH SCHOOL, SUNYANI', 'sda senior high school, sunyani', 'shs', NULL),
  ('S.D.A. SENIOR HIGHSCHOOL, AKIM SEKYERE', 'sda senior highschool, akim sekyere', 'shs', NULL),
  ('SEFWI BEKWAI SENIOR HIGH SCHOOL', 'sefwi bekwai senior high school', 'shs', NULL),
  ('SEFWI-WIAWSO SENIOR HIGH SCHOOL', 'sefwi-wiawso senior high school', 'shs', NULL),
  ('SEFWI-WIAWSO SENIOR HIGH/TECH SCHOOL', 'sefwi-wiawso senior high/tech school', 'technical', NULL),
  ('SEKYEDUMASE SENIOR HIGH/TECH SCHOOL', 'sekyedumase senior high/tech school', 'technical', NULL),
  ('SENYA SENIOR HIGH SCHOOL', 'senya senior high school', 'shs', NULL),
  ('SERWAA KESSE GIRLS SENIOR HIGH SCHOOL', 'serwaa kesse girls senior high school', 'shs', NULL),
  ('SERWAAH NYARKO GIRLS'' SENIOR HIGH SCHOOL', 'serwaah nyarko girls senior high school', 'shs', NULL),
  ('SHAMA SENIOR HIGH SCHOOL', 'shama senior high school', 'shs', NULL),
  ('SHIA SENIOR HIGHTECHNICAL SCHOOL', 'shia senior hightechnical school', 'technical', NULL),
  ('SIDDIQ SENIOR HIGH SCHOOL', 'siddiq senior high school', 'shs', NULL),
  ('SIMMS SENIOR HIGH/COM. SCHOOL', 'simms senior high/com school', 'shs', NULL),
  ('SIRIGU INTEGRATED SENIOR HIGH SCHOOL', 'sirigu integrated senior high school', 'shs', NULL),
  ('SOGAKOPE SENIOR HIGH SCHOOL', 'sogakope senior high school', 'shs', NULL),
  ('SOKODE SENIOR HIGH/TECH SCHOOL', 'sokode senior high/tech school', 'technical', NULL),
  ('SOMBO SENIOR HIGH SCHOOL', 'sombo senior high school', 'shs', NULL),
  ('SOME SENIOR HIGH SCHOOL', 'some senior high school', 'shs', NULL),
  ('SPIRITAN SENIOR HIGH SCHOOL', 'spiritan senior high school', 'shs', NULL),
  ('ST. ANN''S GIRLS SENIOR HIGH SCHOOL, SAMPA', 'st anns girls senior high school, sampa', 'shs', NULL),
  ('ST. ANTHONY OF PADUA SENIOR HIGH/TECH SCHOOL', 'st anthony of padua senior high/tech school', 'technical', NULL),
  ('ST. AUGUSTINE SENIOR HIGH SCHOOL, NSAPOR- BEREKUM', 'st augustine senior high school, nsapor- berekum', 'shs', NULL),
  ('ST. AUGUSTINE SENIOR HIGH/TECH SCHOOL, SAAN CHARIKPONG', 'st augustine senior high/tech school, saan charikpong', 'technical', NULL),
  ('ST. AUGUSTINE''S SENIOR HIGH SCHOOL, BOGOSO', 'st augustines senior high school, bogoso', 'shs', NULL),
  ('ST. CATHERINE GIRLS SENIOR HIGH SCHOOL', 'st catherine girls senior high school', 'shs', NULL),
  ('ST. CHARLES SENIOR HIGH SCHOOL, TAMALE', 'st charles senior high school, tamale', 'shs', NULL),
  ('ST. DOMINIC''S SENIOR HIGH/TECH SCHOOL, PEPEASE', 'st dominics senior high/tech school, pepease', 'technical', NULL),
  ('ST. FIDELIS SENIOR HIGH/TECH SCHOOL', 'st fidelis senior high/tech school', 'technical', NULL),
  ('ST. FRANCIS GIRLS SENIOR HIGH SCHOOL, JIRAPA', 'st francis girls senior high school, jirapa', 'shs', NULL),
  ('ST. FRANCIS SEMINARY/SENIOR HIGH SCHOOL, BUOYEM', 'st francis seminary/senior high school, buoyem', 'shs', NULL),
  ('ST. FRANCIS SENIOR HIGH/TECH SCHOOL, AKIM ODA', 'st francis senior high/tech school, akim oda', 'technical', NULL),
  ('ST. GEORGE''S SENIOR HIGH TECH SCHOOL', 'st georges senior high tech school', 'technical', NULL),
  ('ST. GREGORY CATHOLIC SENIOR HIGH SCHOOL', 'st gregory catholic senior high school', 'shs', NULL),
  ('ST. HUBERT SEM/SENIOR HIGH SCHOOL, KUMASI', 'st hubert sem/senior high school, kumasi', 'shs', NULL),
  ('ST. JAMES SEM & SENIOR HIGH SCHOOL, ABESIM', 'st james sem & senior high school, abesim', 'shs', NULL),
  ('ST. JEROME SENIOR HIGH SCHOOL, ABOFOUR', 'st jerome senior high school, abofour', 'shs', NULL),
  ('ST. JOHN''S GRAMMAR SENIOR HIGH SCHOOL', 'st johns grammar senior high school', 'shs', NULL),
  ('ST. JOHN''S INTEGRATED SENIOR HIGH/TECH SCHOOL', 'st johns integrated senior high/tech school', 'technical', NULL),
  ('ST. JOHN''S SENIOR HIGH SCHOOL, SEKONDI', 'st johns senior high school, sekondi', 'shs', NULL),
  ('ST. JOSEPH SEM/SENIOR HIGH SCHOOL, MAMPONG', 'st joseph sem/senior high school, mampong', 'shs', NULL),
  ('ST. JOSEPH SENIOR HIGH SCHOOL, SEFWI WIAWSO', 'st joseph senior high school, sefwi wiawso', 'shs', NULL),
  ('ST. JOSEPH SENIOR HIGH/TECH SCHOOL, AHWIREN', 'st joseph senior high/tech school, ahwiren', 'technical', NULL),
  ('ST. LOUIS SENIOR HIGH SCHOOL, KUMASI', 'st louis senior high school, kumasi', 'shs', NULL),
  ('ST. MARGARET MARY SENIOR HIGH/TECH SCHOOL', 'st margaret mary senior high/tech school', 'technical', NULL),
  ('ST. MARTIN''S SENIOR HIGH SCHOOL, NSAWAM', 'st martins senior high school, nsawam', 'shs', NULL),
  ('ST. MARY''S BOYS'' SENIOR HIGH SCHOOL, APOWA', 'st marys boys senior high school, apowa', 'shs', NULL),
  ('ST. MARY''S SEM.& SENIOR HIGH SCHOOL, LOLOBI', 'st marys sem& senior high school, lolobi', 'shs', NULL),
  ('ST. MARY''S SENIOR HIGH SCHOOL, KORLE GONNO', 'st marys senior high school, korle gonno', 'shs', NULL),
  ('ST. MICHAEL''S SENIOR HIGH SCHOOL, AHENKRO', 'st michaels senior high school, ahenkro', 'shs', NULL)
ON CONFLICT (name_norm) DO NOTHING;

INSERT INTO senior_high_schools (name, name_norm, school_type, region)
VALUES
  ('ST. MICHAEL''S SENIOR HIGH SCHOOL, AKOASE (NKAWKAW)', 'st michaels senior high school, akoase (nkawkaw)', 'shs', NULL),
  ('ST. MONICA''S SENIOR HIGH SCHOOL, MAMPONG', 'st monicas senior high school, mampong', 'shs', NULL),
  ('ST. PAUL''S SENIOR HIGH SCHOOL, ASAKRAKA KWAHU', 'st pauls senior high school, asakraka kwahu', 'shs', NULL),
  ('ST. PAUL''S SENIOR HIGH SCHOOL, DENU', 'st pauls senior high school, denu', 'shs', NULL),
  ('ST. PAUL''S TECH. SCHOOL', 'st pauls tech school', 'technical', NULL),
  ('ST. PETER''S SENIOR HIGH SCHOOL, NKWATIA', 'st peters senior high school, nkwatia', 'shs', NULL),
  ('ST. ROSE''S SENIOR HIGH SCHOOL, AKWATIA', 'st roses senior high school, akwatia', 'shs', NULL),
  ('ST. SEBASTIAN CATH. SENIOR HIGH SCHOOL', 'st sebastian cath senior high school', 'shs', NULL),
  ('ST. STEPHEN''S PRESBY SENIOR HIGH/TECH SCHOOL, ASIAKWA', 'st stephens presby senior high/tech school, asiakwa', 'technical', NULL),
  ('ST. THOMAS AQUINAS SENIOR HIGH SCHOOL, CANTOMENTS', 'st thomas aquinas senior high school, cantoments', 'shs', NULL),
  ('ST. THOMAS SENIOR HIGH/TECH SCHOOL', 'st thomas senior high/tech school', 'technical', NULL),
  ('SUHUM SENIOR HIGH/TECH SCHOOL', 'suhum senior high/tech school', 'technical', NULL),
  ('SUMAMAN SENIOR HIGH SCHOOL', 'sumaman senior high school', 'shs', NULL),
  ('SUNYANI SENIOR HIGH SCHOOL', 'sunyani senior high school', 'shs', NULL),
  ('SWEDRU SENIOR HIGH SCHOOL', 'swedru senior high school', 'shs', NULL),
  ('T. I. AHMADIYYA GIRL''S SENIOR HIGH SCHOOL, ASOKORE', 't i ahmadiyya girls senior high school, asokore', 'shs', NULL),
  ('T. I. AHMADIYYA SENIOR HIGH SCHOOL, KUMASI', 't i ahmadiyya senior high school, kumasi', 'shs', NULL),
  ('T. I. AHMADIYYA SENIOR HIGH SCHOOL, WA', 't i ahmadiyya senior high school, wa', 'shs', NULL),
  ('TAKORADI SENIOR HIGH SCHOOL', 'takoradi senior high school', 'shs', NULL),
  ('TAKPO SENIOR HIGH SCHOOL', 'takpo senior high school', 'shs', NULL),
  ('TAMALE GIRLS SENIOR HIGH SCHOOL', 'tamale girls senior high school', 'shs', NULL),
  ('TAMALE SENIOR HIGH SCHOOL', 'tamale senior high school', 'shs', NULL),
  ('TANYIGBE SENIOR HIGH SCHOOL', 'tanyigbe senior high school', 'shs', NULL),
  ('TAPAMAN SENIOR HIGH/TECH SCHOOL', 'tapaman senior high/tech school', 'technical', NULL),
  ('TARKROSI COMM. SENIOR HIGH SCHOOL', 'tarkrosi comm senior high school', 'shs', NULL),
  ('TARKWA SENIOR HIGH SCHOOL', 'tarkwa senior high school', 'shs', NULL),
  ('TAVIEFE COMM. SENIOR HIGH SCHOOL', 'taviefe comm senior high school', 'shs', NULL),
  ('TAWHEED SENIOR HIGH SCHOOL', 'tawheed senior high school', 'shs', NULL),
  ('TECHIMAN SENIOR HIGH SCHOOL', 'techiman senior high school', 'shs', NULL),
  ('TEMA MANHEAN SENIOR HIGH/TECH SCHOOL', 'tema manhean senior high/tech school', 'technical', NULL),
  ('TEMA METH. DAY SENIOR HIGH SCHOOL', 'tema meth day senior high school', 'shs', NULL),
  ('TEMA SENIOR HIGH SCHOOL', 'tema senior high school', 'shs', NULL),
  ('TEMPANE SENIOR HIGH SCHOOL', 'tempane senior high school', 'shs', NULL),
  ('TEPA SENIOR HIGH SCHOOL', 'tepa senior high school', 'shs', NULL),
  ('TERCHIRE SENIOR HIGH SCHOOL', 'terchire senior high school', 'shs', NULL),
  ('THREE TOWN SENIOR HIGH SCHOOL', 'three town senior high school', 'shs', NULL),
  ('TIJJANIYA SENIOR HIGH SCHOOL', 'tijjaniya senior high school', 'shs', NULL),
  ('TOASE SENIOR HIGH SCHOOL', 'toase senior high school', 'shs', NULL),
  ('TOLON SENIOR HIGH SCHOOL', 'tolon senior high school', 'shs', NULL),
  ('TONGO SENIOR HIGH/TECH SCHOOL', 'tongo senior high/tech school', 'technical', NULL),
  ('TONGOR SENIOR HIGH TECH SCHOOL', 'tongor senior high tech school', 'technical', NULL),
  ('TSIAME SENIOR HIGH SCHOOL', 'tsiame senior high school', 'shs', NULL),
  ('TSITO SENIOR HIGH/TECH SCHOOL', 'tsito senior high/tech school', 'technical', NULL),
  ('TUMU SENIOR HIGH/TECH SCHOOL', 'tumu senior high/tech school', 'technical', NULL),
  ('TUNA SENIOR HIGH/TECH SCHOOL', 'tuna senior high/tech school', 'technical', NULL),
  ('TUOBODOM SENIOR HIGH/TECH SCHOOL', 'tuobodom senior high/tech school', 'technical', NULL),
  ('TWEAPEASE SENIOR HIGH SCHOOL', 'tweapease senior high school', 'shs', NULL),
  ('TWENE AMANFO SENIOR HIGH/TECH SCHOOL', 'twene amanfo senior high/tech school', 'technical', NULL),
  ('TWENEBOA KODUA SENIOR HIGH SCHOOL', 'tweneboa kodua senior high school', 'shs', NULL),
  ('TWIFO HEMANG SENIOR HIGH/TECH SCHOOL', 'twifo hemang senior high/tech school', 'technical', NULL),
  ('TWIFO PRASO SENIOR HIGH SCHOOL', 'twifo praso senior high school', 'shs', NULL),
  ('ULLO SENIOR HIGH SCHOOL', 'ullo senior high school', 'shs', NULL),
  ('UNIVERSITY PRACTICE SENIOR HIGH SCHOOL', 'university practice senior high school', 'shs', NULL),
  ('UTHMAN BIN AFAM SENIOR HIGH SCHOOL', 'uthman bin afam senior high school', 'shs', NULL),
  ('UTHMANIYA SENIOR HIGH SCHOOL, TAFO', 'uthmaniya senior high school, tafo', 'shs', NULL),
  ('VAKPO SENIOR HIGH SCHOOL', 'vakpo senior high school', 'shs', NULL),
  ('VAKPO SENIOR HIGH/TECH SCHOOL', 'vakpo senior high/tech school', 'technical', NULL),
  ('VE COMM. SENIOR HIGH SCHOOL', 've comm senior high school', 'shs', NULL),
  ('VOLO COMM. SENIOR HIGH SCHOOL', 'volo comm senior high school', 'shs', NULL),
  ('VOLTA SENIOR HIGH SCHOOL', 'volta senior high school', 'shs', NULL),
  ('WA SENIOR HIGH SCHOOL', 'wa senior high school', 'shs', NULL),
  ('WA SENIOR HIGH/TECH SCHOOL', 'wa senior high/tech school', 'technical', NULL),
  ('WALEWALE SENIOR HIGH SCHOOL', 'walewale senior high school', 'shs', NULL),
  ('WAMANAFO SENIOR HIGH/TECH SCHOOL', 'wamanafo senior high/tech school', 'technical', NULL),
  ('WAPULI COMM. SENIOR HIGH SCHOOL', 'wapuli comm senior high school', 'shs', NULL),
  ('W.B.M. ZION SENIOR HIGH SCHOOL, OLD TAFO', 'wbm zion senior high school, old tafo', 'shs', NULL),
  ('WENCHI METH. SENIOR HIGH SCHOOL', 'wenchi meth senior high school', 'shs', NULL),
  ('WESLEY GIRLS SENIOR HIGH SCHOOL, CAPE COAST', 'wesley girls senior high school, cape coast', 'shs', NULL),
  ('WESLEY GRAMMAR SENIOR HIGH SCHOOL', 'wesley grammar senior high school', 'shs', NULL),
  ('WESLEY HIGH SCHOOL, BEKWAI', 'wesley high school, bekwai', 'shs', NULL),
  ('WESLEY SENIOR HIGH SCHOOL, KONONGO', 'wesley senior high school, konongo', 'shs', NULL),
  ('WEST AFRICA SENIOR HIGH SCHOOL', 'west africa senior high school', 'shs', NULL),
  ('WETA SENIOR HIGH/TECH SCHOOL', 'weta senior high/tech school', 'technical', NULL),
  ('WIAFE AKENTEN PRESBY SENIOR HIGH SCHOOL', 'wiafe akenten presby senior high school', 'shs', NULL),
  ('WIAGA COMM. SENIOR HIGH SCHOOL', 'wiaga comm senior high school', 'shs', NULL),
  ('WINNEBA SENIOR HIGH SCHOOL', 'winneba senior high school', 'shs', NULL),
  ('WORAWORA SENIOR HIGH SCHOOL', 'worawora senior high school', 'shs', NULL),
  ('WOVENU SENIOR HIGH TECHNICAL SCHOOL', 'wovenu senior high technical school', 'technical', NULL),
  ('WULENSI SENIOR HIGH SCHOOL', 'wulensi senior high school', 'shs', NULL),
  ('WULUGU SENIOR HIGH SCHOOL', 'wulugu senior high school', 'shs', NULL)
ON CONFLICT (name_norm) DO NOTHING;

INSERT INTO senior_high_schools (name, name_norm, school_type, region)
VALUES
  ('YAA ASANTEWAA GIRLS SENIOR HIGH SCHOOL', 'yaa asantewaa girls senior high school', 'shs', NULL),
  ('YABRAM COMM. DAY SCHOOL', 'yabram comm day school', 'shs', NULL),
  ('YAGABA SENIOR HIGH SCHOOL', 'yagaba senior high school', 'shs', NULL),
  ('YAMFO ANGLICAN SENIOR HIGH SCHOOL', 'yamfo anglican senior high school', 'shs', NULL),
  ('YEBOAH ASUAMAH SENIOR HIGH SCHOOL', 'yeboah asuamah senior high school', 'shs', NULL),
  ('YEJI SENIOR HIGH/TECH SCHOOL', 'yeji senior high/tech school', 'technical', NULL),
  ('YENDI SENIOR HIGH SCHOOL', 'yendi senior high school', 'shs', NULL),
  ('YILO KROBO SENIOR HIGH/COMM SCHOOL', 'yilo krobo senior high/comm school', 'shs', NULL),
  ('ZABZUGU SENIOR HIGH SCHOOL', 'zabzugu senior high school', 'shs', NULL),
  ('ZAMSE SENIOR HIGH/TECH SCHOOL', 'zamse senior high/tech school', 'technical', NULL),
  ('ZEBILLA SENIOR HIGH/TECH SCHOOL', 'zebilla senior high/tech school', 'technical', NULL),
  ('ZION SENIOR HIGH SCHOOL', 'zion senior high school', 'shs', NULL),
  ('ZIOPE SENIOR HIGH SCHOOL', 'ziope senior high school', 'shs', NULL),
  ('ZORKOR SENIOR HIGH SCHOOL', 'zorkor senior high school', 'shs', NULL),
  ('ZUARUNGU SENIOR HIGH SCHOOL', 'zuarungu senior high school', 'shs', NULL)
ON CONFLICT (name_norm) DO NOTHING;
